# Generated by Django 3.2.8 on 2021-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField()),
                ('promotion', models.CharField(max_length=30)),
            ],
        ),
    ]
