# Generated by Django 3.2.8 on 2021-10-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0002_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='promotion',
        ),
    ]
