# Generated by Django 3.2.8 on 2021-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0003_remove_menu_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
