# Generated by Django 3.2.8 on 2021-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0003_remove_menu_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
