# Generated by Django 3.2.8 on 2021-11-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0004_alter_menu_status'),
        ('easyRestaurant_web', '0004_auto_20211104_2100'),
    ]

    operations = [
    ]
