# Generated by Django 3.2.8 on 2021-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0004_auto_20211104_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image_promotion')),
                ('name2', models.CharField(max_length=20)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image_promotion')),
                ('name3', models.CharField(max_length=20)),
                ('price3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imag4', models.ImageField(blank=True, null=True, upload_to='image_promotion')),
                ('name4', models.CharField(max_length=20)),
                ('price4', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_menu'),
        ),
    ]
