# Generated by Django 3.2.8 on 2021-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0005_auto_20211106_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_promotion',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image_promotion'),
        ),
    ]
