# Generated by Django 3.2.8 on 2021-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0005_merge_0004_alter_menu_status_0004_auto_20211104_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_menu'),
        ),
    ]
