# Generated by Django 3.2.8 on 2021-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0006_image_promotion_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_promotion',
            name='imag4',
        ),
        migrations.AddField(
            model_name='image_promotion',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='image_promotion'),
        ),
    ]
