# Generated by Django 3.2.8 on 2021-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0007_auto_20211106_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_pagemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_pagemanu')),
            ],
        ),
    ]
