# Generated by Django 3.2.8 on 2021-11-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0006_alter_menu_image'),
        ('easyRestaurant_web', '0009_image_main'),
    ]

    operations = [
    ]
