# Generated by Django 3.2.8 on 2021-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0010_merge_0006_alter_menu_image_0009_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_main',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
