# Generated by Django 3.2.8 on 2021-12-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
