# Generated by Django 3.2.8 on 2021-12-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0013_table'),
        ('easyRestaurant_web', '0014_cart_cartitem'),
    ]

    operations = [
    ]
