# Generated by Django 3.2.8 on 2021-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyRestaurant_web', '0015_alter_order_email'),
        ('easyRestaurant_web', '0015_merge_0013_table_0014_cart_cartitem'),
    ]

    operations = [
    ]
